name: Create Production Deployment

on:
  workflow_dispatch:

jobs:
  create-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: staging
          target_branch: prod
          id: create_pr
          title: ${{ steps.date.outputs.date }} Production Deployment
