name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          base: staging
          head: dev
          title: "$(date +%Y%m%d%H%M) Staging Deployment"

      - name: Get pull request URL
        id: pr_url
        run: echo "Pull Request URL ${{ steps.create_pull_request.outputs['pull-request-url'] }}"
