name: Create Production Deployment

on:
  workflow_dispatch:

jobs:
  create-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        id: create_pr
        with:
          base: prod
          branch: staging
          title: "$(date +%Y%m%d%H%M) Production Deployment"

      - name: Get pull request URL
        id: pr_url
        run: echo "Pull Request URL ${{ steps.create_pr.pull-request-url }}"
