name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ endsWith(github.event.head_commit.message, 'Staging Deployment')}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to staging environment
        # TODO: trigger deployment
        run: echo Deploying Staging
