name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          base: staging
          head: dev
          title: 'Merge dev to staging for deployment'
          body: 'This is an automated pull request for deploying dev to staging environment.'

      - name: Get pull request URL
        id: pr_url
        run: echo "Pull Request URL: ${{ steps.create_pull_request.outputs.pull-request-url }}"

      - name: Wait for pull request to merge
        uses: peter-evans/wait-for-merge@v1
        with:
          pull-request-number: ${{ steps.create_pull_request.outputs.pull-request-number }}

      - name: Checkout staging branch
        uses: actions/checkout@v2
        with:
          ref: staging

      - name: Deploy to staging environment
        run: make deploy-staging
